### ISSUE TITLE
ASM error: Class versions V1_5 or less must use F_NEW frames.

### ISSUE THREAD

**Issue by TheDGOfficial** [Sipkab/jvm-tail-recursion#6]
I'm getting this error:

```
Exception in thread "main" java.lang.IllegalArgumentException: Class versions V1_5 or less must use F_NEW frames.
        at sipka.jvm.tailrec.thirdparty.org.objectweb.asm.MethodWriter.visitFrame(MethodWriter.java:779)
        at sipka.jvm.tailrec.thirdparty.org.objectweb.asm.tree.FrameNode.accept(FrameNode.java:141)
        at sipka.jvm.tailrec.thirdparty.org.objectweb.asm.tree.InsnList.accept(InsnList.java:145)
        at sipka.jvm.tailrec.thirdparty.org.objectweb.asm.tree.MethodNode.accept(MethodNode.java:752)
        at sipka.jvm.tailrec.thirdparty.org.objectweb.asm.tree.MethodNode.accept(MethodNode.java:650)
        at sipka.jvm.tailrec.thirdparty.org.objectweb.asm.tree.ClassNode.accept(ClassNode.java:466)
        at sipka.jvm.tailrec.TailRecursionOptimizer.optimizeMethods(TailRecursionOptimizer.java:114)
        at sipka.jvm.tailrec.TailRecursionOptimizer.optimizeMethods(TailRecursionOptimizer.java:92)
        at sipka.jvm.tailrec.MainCommand.optimizeJar(MainCommand.java:208)
        at sipka.jvm.tailrec.MainCommand.optimizeFile(MainCommand.java:182)
        at sipka.jvm.tailrec.MainCommand.call(MainCommand.java:139)
        at sipka.jvm.tailrec.Main.lambda$parse$1(Main.java:166)
        at sipka.jvm.tailrec.Main.callCommand(Main.java:195)
        at sipka.jvm.tailrec.Main.main(Main.java:177)
```

Version: v0.8.1
Java version used to run: Java 15

The target JAR uses Java 8 as far as I know, but it has some libraries that should be backwards compatible or such for my understanding, otherwise who would on the earth still uses Java 5? There is Java 15!

**Comment by Sipkab** [comment]
Hi, thanks for the report, I'll take a look at it when I have some free time. (May be during this or the next week.)

**Comment by TheDGOfficial** [comment]
Any updates on this?

**Comment by Sipkab** [comment]
Sorry, I didn't have much time for this, don't have an ETA yet.

**Comment by scompton93** [comment]
@Sipkab Did you ever get around to this? No pressure, just curious.
